version: '3.8'

services:
  openms-streamlit-template:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GITHUB_TOKEN: $GITHUB_TOKEN
    image: mzcalculator
    container_name: mzcalculator
    restart: always
    ports:
      - 8501:8501
    volumes:
      - workspaces-mzcalculator:/workspaces-mzcalculator
    command: streamlit run peptide-mz-calculator/app.py
volumes:
  workspaces-mzcalculator:
