name: Test workflow functions

on:
  push:
    branches: [ "main", "week-*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
    - name: Run unit tests
      run: |
        pytest tests/ -v
      env:
        PYTHONPATH: .
    - name: Run GUI tests
      run: |
        pytest test_gui.py -v
      env:
        PYTHONPATH: .